### ISSUE TITLE
M365 login - forwarded to device.login.domain.my

### ISSUE THREAD

**Issue by maltic42** [BakkerJan/evilginx3#5]
Hi,
after settings up Evilginx 3.2.0 with your M365 phishlet and configuring everything the following happens: after logging in to the URL (login.domain.my/randomtoken) I am prompted for a login, then a password. Both are logged. After that the browser is forwarded to device.login.domain.my and times out. I am not prompted for an MFA, I just get a browser message because of the timeout. I already created a DNS entry for device.login.domain.my, but this does not help. Any suggestions?
Thanks!

**Comment by Nemeziz50** [comment]
I’ll suggest  reinstall it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: maltic42 ***@***.***>
Sent: Tuesday, March 19, 2024 6:04:33 PM
To: BakkerJan/evilginx3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BakkerJan/evilginx3] M365 login - forwarded to device.login.domain.my (Issue #5)


Hi,
after settings up Evilginx 3.2.0 with your M365 phishlet and configuring everything the following happens: after logging in to the URL (login.domain.my/randomtoken) I am prompted for a login, then a password. Both are logged. After that the browser is forwarded to device.login.domain.my and times out. I am not prompted for an MFA, I just get a browser message because of the timeout. I already created a DNS entry for device.login.domain.my, but this does not help. Any suggestions?
Thanks!

**Comment by maltic42** [comment]
What do you recommend to reinstall? Evilginx?

Edit: Reinstalling Evilginx and deleting .evilginx does not work - same problem.

**Comment by maltic42** [comment]
Nevermind, got it up and running, I had to make some changes to the phishlet. Thanks.
